---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: healthcare-container
          image: varunv25/myimg1:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: medicure
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: medicure   # ✅ Corrected — no trailing dot
